import 'package:flutter/material.dart';

class Song {
  String title;
  String imageUrl;
  int site;
  int currSite;
  String type;
  int howMuchSites;
  Song(
  { required this.title,
    required this.imageUrl,
    required this.type,
    required this.currSite,
    required this.howMuchSites,
    required this.site});
  String nextSite(int i);

  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
List<Song> currentMass = [
  Song(
    title:  "Msza Pokoju - Panie, zmiłuj się",
    site:  13,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-013.png",
    type: "Msza Pokoju",
    howMuchSites: 1,
    currSite: 13,
  ),
  Song(
    title:  "Msza Pokoju - Panie, zmiłuj się",
    site:  13,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-013.png",
    type: "Msza Pokoju",
    howMuchSites: 1,
    currSite: 13,
  ),
  Song(
    title:  "Msza Pokoju - Panie, zmiłuj się",
    site:  13,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-013.png",
    type: "Msza Pokoju",
    howMuchSites: 1,
    currSite: 13,
  ),
];
List<Song> songList = [
  Song(
    title:  "Msza Pokoju - Panie, zmiłuj się",
    site:  13,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-013.png",
    type: "Msza Pokoju",
    howMuchSites: 1,
    currSite: 13,
  ),
  Song(
    title:  "Msza Pokoju - Święty",
    site:  14,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-014.png",
    type: "Msza Pokoju",
      howMuchSites: 2,
    currSite: 14,
  ),
  Song(
    title:  "Msza Pokoju - Baranku Boży",
    site:  15,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-015.png",
    type: "Msza Pokoju",
    howMuchSites: 1,
    currSite: 15,
  ),
  Song(
      title: "Msza św. Faustyny - Panie, zmiłuj się",
      site: 16,
      imageUrl: "lib/Screens/pictures/NŚM v.2.0-016.png",
      type: "Msza św. Faustyny",
      howMuchSites: 1,
      currSite: 16,
  ),
  Song(
      title: "Msza św. Faustyny - Święty",
      site: 18,
      imageUrl: "lib/Screens/pictures/NŚM v.2.0-018.png",
      type: "Msza św. Faustyny",
      howMuchSites: 2,
      currSite: 18,
  ),
  Song(
      title: "Msza św. Faustyny - Baranku Boży",
      site: 17,
      imageUrl: "lib/Screens/pictures/NŚM v.2.0-017.png",
      type: "Msza św. Faustyny",
      howMuchSites: 1,
      currSite: 17
  ),
  Song(
      title: "Msza św. Macieja - Panie, zmiłuj się",
      site: 20,
      imageUrl: "lib/Screens/pictures/NŚM v.2.0-020.png",
      type: "Msza św. Macieja",
      howMuchSites: 1,
      currSite: 20,

  ),
  Song(
      title: "Msza św. Macieja - Święty",
      site: 21,
      imageUrl: "lib/Screens/pictures/NŚM v.2.0-020.png",
      type: "Msza św. Macieja",
      howMuchSites: 2,
      currSite: 21,
  ),
  Song(
      title: "Msza św. Macieja - Baranku Boży",
      site: 23,
      imageUrl: "lib/Screens/pictures/NŚM v.2.0-022.png",
      type: "Msza św. Macieja",
      howMuchSites: 1,
      currSite: 22,
  ),

  Song(
    title: "Ojcze nasz",
    site: 22,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-022.png",
    type: "modlitwa",
    howMuchSites: 1,
    currSite: 22,
  ),
  Song(
    title: "Litania loretańska",
    site: 23,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-023.png",
    type: "modlitwa",
    howMuchSites: 1,
    currSite: 23,
  ),
  Song(
    title: "Anioł Pański",
    site: 24,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-024.png",
    type: "modlitwa",
    howMuchSites: 2,
    currSite: 24,
  ),
  Song(
    title: "Koronka do Miłosierdzia Bożego",
    site: 26,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-026.png",
    type: "modlitwa",
    howMuchSites: 2,
    currSite: 26,
  ),
  Song(
    title: "Gorzkie Żale",
    site: 27,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-027.png",
    type: "modlitwa",
    howMuchSites: 7,
    currSite: 27,
  ),
  Song(
    title: "Alleluja (by moje serce)",
    site: 34,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-034.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 34,
  ),
  Song(
    title: "Alleluja (światłość prawdziwa)",
    site: 36,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-036.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 36,
  ),
  Song(
    title: "Archanioł Boży Gabryjel",
    site: 37,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-037.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 37,
  ),
  Song(
    title: "Ave Maria",
    site: 38,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-038.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 38,
  ),
  Song(
    title: "Bądź mi litośćiw",
    site: 39,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-039.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 39,
  ),
  Song(
    title: "Będę Cię chwalił Boże",
    site: 40,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-040.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 40,
  ),
  Song(
    title: "Będę Cię wysławiał",
    site: 41,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-041.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 41,
  ),
  Song(
    title: "Będę śpiewał Tobie",
    site: 41,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-041.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 41,
  ),
  Song(
    title: "Bliskie jest Królestwo Boże",
    site: 42,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-042.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 42,
  ),
  Song(
    title: "Błogosławcie Pana",
    site: 42,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-042.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 42,
  ),
  Song(
    title: "Błogosławiony Pan",
    site: 43,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-043.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 43,
  ),
  Song(
    title: "Błogosławcie Pana (chór i soliści)",
    site: 44,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-044.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 44,
  ),
  Song(
    title: "Bogurodzica",
    site: 0,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-046.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 46,
  ),
  Song(
    title: "Boska dobroci",
    site: 47,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-047.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 47,
  ),
  Song(
    title: "Boże, coś Polskę",
    site: 49,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-049.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 49,
  ),
  Song(
    title: "Boże, mój Boże",
    site: 49,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-049.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 49,
  ),
  Song(
    title: "Boże, obdarz Kościół Twój",
    site: 50,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-050.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 50,
  ),
  Song(
    title: "Chleb Żywy",
    site: 50,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-050.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 50,
  ),
  Song(
    title: "Christe Jesu lumen cordium",
    site: 50,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-050.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 50,
  ),
  Song(
    title: "Cała ziemio wołaj",
    site: 51,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-051.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 51,
  ),
  Song(
    title: "Choćbym szedł ciemną doliną",
    site: 52,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-052.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 52,
  ),
  Song(
    title: "Chrystus Pan",
    site: 52,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-052.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 52,
  ),
  Song(
    title: "Chrystus Wodzem",
    site: 53,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-053.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 53,
  ),
  Song(
    title: "Chrystus zmartwychwstan jest",
    site: 54,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-054.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 54,
  ),
  Song(
    title: "Chrześcijanie klaszczcie w dłonie",
    site: 55,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-055.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 55,
  ),
  Song(
    title: "Chwalcie łąki umajone",
    site: 56,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-056.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 56,
  ),
  Song(
    title: "Ci, którzy we łzach sieją",
    site: 56,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-056.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 56,
  ),
  Song(
    title: "Ciebie, Boga wysławiamy",
    site: 58,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-058.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 58,
  ),
  Song(
    title: "Ciebie całą dyszą pragnę",
    site: 59,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-059.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 59,
  ),
  Song(
    title: "Com przyrzekł Bogu",
    site: 60,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-060.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 60,
  ),
  Song(
    title: "Communio",
    site: 61,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-061.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 61,
  ),
  Song(
    title: "Czego chcesz od nas, Panie",
    site: 61,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-061.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 61,
  ),
  Song(
    title: "De profundis",
    site: 62,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-062.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 62,
  ),
  Song(
    title: "Do Anioła Stróża",
    site: 62,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-062.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 62,
  ),
  Song(
    title: "Do Ciebie Panie",
    site: 63,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-063.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 63,
  ),
  Song(
    title: "Dobranoc głowo święta",
    site: 64,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-064.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 64,
  ),
  Song(
    title: "Dobroć i łaska",
    site: 65,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-065.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 65,
  ),
  Song(
    title: "Dobry Bóg",
    site: 66,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-066.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 66,
  ),
  Song(
    title: "Dobry jest Pan",
    site: 67,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-067.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 67,
  ),
  Song(
    title: "Duch i ogień",
    site: 68,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-068.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 68,
  ),
  Song(
    title: "Duch Pański nade mną",
    site: 69,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-069.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 69,
  ),
  Song(
    title: "Duch Pański napełnił okrąg ziemi",
    site: 70,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-070.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 70,
  ),
  Song(
    title: "Duchu Ogniu, Duchu Żarze",
    site: 71,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-071.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 71,
  ),
  Song(
    title: "Duszo Chrystusowa",
    site: 72,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-072.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 72,
  ),
  Song(
    title: "Duchu Stworzycielu",
    site: 73,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-073.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 73,
  ),
  Song(
    title: "Dzięki Ci Panie",
    site: 74,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-074.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 74,
  ),
  Song(
    title: "Dzieci żydowskie",
    site: 75,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-075.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 75,
  ),
  Song(
    title: "Gamul",
    site: 76,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-076.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 76,
  ),
  Song(
    title: "Gloria Patri et Filio",
    site: 76,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-076.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 76,
  ),
  Song(
    title: "Gloria Tibi Domine",
    site: 77,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-077.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 77,
  ),
  Song(
    title: "Głoś imię Pana",
    site: 77,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-077.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 77,
  ),
  Song(
    title: "Grzechem Adama",
    site: 78,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-078.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 78,
  ),
  Song(
    title: "Gwiazdo morza głębokiego",
    site: 79,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-079.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 79,
  ),
  Song(
    title: "Hejnał",
    site: 80,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-080.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 80,
  ),
  Song(
    title: "Hosanna Synowi Dawidowemu",
    site: 81,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-081.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 81,
  ),
  Song(
    title: "Hymn etiopski",
    site: 81,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-081.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 81,
  ),
  Song(
    title: "Hymn ku czci Krzyża Świętego",
    site: 82,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-082.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 82,
  ),
  Song(
    title: "Idźcie na cały świat",
    site: 83,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-084.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 83,
  ),
  Song(
    title: "Hymn o miłości",
    site: 84,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-084.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 84,
  ),
  Song(
    title: "Jakże pójdziemy za Tobą Chrystusie",
    site: 86,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-086.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 86,
  ),
  Song(
    title: "Jam jest Chleb Życia",
    site: 87,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-087.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 87,
  ),
  Song(
    title: "Jeden Chleb",
    site: 88,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-088.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 88,
  ),
  Song(
    title: "Jedynie w Bogu",
    site: 88,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-088.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 88,
  ),
  Song(
    title: "Jesteśmy piękni",
    site: 89,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-089.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 89,
  ),
  Song(
    title: "Jesteśmy Twoją własnością",
    site: 90,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-090.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 90,
  ),
  Song(
    title: "Jezu Chryste, Panie miły",
    site: 91,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-091.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 91,
  ),
  Song(
    title: "Jezu, ufam Tobie",
    site: 91,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-091.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 91,
  ),
  Song(
    title: "Już od rana rozśpiewana",
    site: 92,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-092.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 92,
  ),
  Song(
    title: "Kiedy przyjdziesz",
    site: 93,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-093.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 93,
  ),
  Song(
    title: "Krzyżu Chrystusa",
    site: 93,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-093.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 93,
  ),
  Song(
    title: "Kantyk o Męce Pańskiej",
    site: 94,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-094.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 94,
  ),
  Song(
    title: "Krzyżu, mój Krzyżu",
    site: 96,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-096.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 96,
  ),
  Song(
    title: "Krzyżu Święty",
    site: 97,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-097.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 97,
  ),
  Song(
    title: "Kto się w opiekę",
    site: 98,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-098.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 98
  ),
  Song(
    title: "Kto spożywa (Na komunię)",
    site: 99,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-099.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 99,
  ),
  Song(
    title: "Lud Twój, Panie (Chleb pielgrzymów)",
    site: 100,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-100.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 100,
  ),
  Song(
    title: "Ludu, mój ludu",
    site: 101,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-101.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 101,
  ),
  Song(
    title: "Ludu kapłański",
    site: 102,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-102.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 102,
  ),
  Song(
    title: "Łaska Pana",
    site: 103,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-103.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 103,
  ),
  Song(
    title: "Łąki Twoich obietnic",
    site: 103,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-103.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 103,
  ),
  Song(
    title: "Maranatha, przyjdź Panie, przyjdź",
    site: 104,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-104.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 104,
  ),
  Song(
    title: "Mądrości, która (Siedem antyfon adwentowych)",
    site: 105,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-105.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 105,
  ),
  Song(
    title: "Matko Najpiękniejszego",
    site: 106,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-106.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 106,
  ),
  Song(
    title: "Maryjo, prześliczna Pani",
    site: 107,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-107.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 106,
  ),
  Song(
    title: "Mądrość stół zastawiła",
    site: 108,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-108.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 108,
  ),
  Song(
    title: "Miłosierny Pan i łaskawy",
    site: 110,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-110.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 110,
  ),
  Song(
    title: "Mądrość doda wam skrzydeł",
    site: 111,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-111.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 111,
  ),
  Song(
    title: "Miłość nigdy nie ustaje",
    site: 111,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-111.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 111,
  ),
  Song(
    title: "Miłujcie się wzajemnie",
    site: 112,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-112.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 112,
  ),
  Song(
    title: "Miłuję Cię Panie",
    site: 113,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-113.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 113,
  ),
  Song(
    title: "Modlitwa o skruchę",
    site: 114,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-114.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 114,
  ),
  Song(
    title: "Moja nadzieja",
    site: 115,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-115.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 115,
  ),
  Song(
    title: "Modlitwa szabasowa",
    site: 116,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-116.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 116,
  ),
  Song(
    title: "Moje serce zaufało Panu",
    site: 118,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-118.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 118,
  ),
  Song(
    title: "Nasza droga",
    site: 119,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-119.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 119,
  ),
  Song(
    title: "Naucz nas trwać",
    site: 120,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-120.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 120,
  ),
  Song(
    title: "Nic nas nie zdoła odłączyć (Pieśń o Miłości)",
    site: 120,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-120.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 120,
  ),
  Song(
    title: "Nie bójcie się żyć dla Miłości",
    site: 121,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-121.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 121,
  ),
  Song(
    title: "Nie ma dla mnie",
    site: 121,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-121.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 121,
  ),
  Song(
    title: "Nie użyczę (modlitwa orzed snem)",
    site: 122,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-122.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 122,
  ),
  Song(
    title: "Nie zna śmierci",
    site: 122,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-122.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 122,
  ),
  Song(
    title: "Niebiosa, rosę ślijcie",
    site: 123,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-123.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 123,
  ),
  Song(
    title: "Niebo pełne Ciebie",
    site: 124,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-124.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 124,
  ),
  Song(
    title: "Niech mnie strzeże Twa święta Krew",
    site: 125,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-125.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 125,
  ),
  Song(
    title: "Niech oblicze Twe",
    site: 125,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-125.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 125,
  ),
  Song(
    title: "Niech Twój rozbłyśnie dzień (Pieśń tęsknoty)",
    site: 126,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-126.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 126,
  ),
  Song(
    title: "Niechaj Cię Panie",
    site: 126,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-126.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 126,
  ),
  Song(
    title: "Niech wam z Syjonu",
    site: 127,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-127.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 127,
  ),
  Song(
    title: "Niepojęta Trójco",
    site: 128,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-128.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 128,
  ),
  Song(
    title: "Nieście chwałę mocarze",
    site: 130,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-130.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 130,
  ),
  Song(
    title: "O krwi najdroższa",
    site: 131,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-131.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 131,
  ),
  Song(
    title: "O Matko miłościwa",
    site: 131,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-131.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 131,
  ),
  Song(
    title: "O Matko z częstochowskiego wizerunku",
    site: 132,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-132.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 132,
  ),
  Song(
    title: "O Pani, ufność nasza",
    site: 133,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-133.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 133,
  ),
  Song(
    title: "O Panie szukasz dzieci Twych",
    site: 133,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-133.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 133,
  ),
  Song(
    title: "O Panie, Ty nam dajesz",
    site: 134,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-134.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 134,
  ),
  Song(
    title: "O salutaris Hostia",
    site: 135,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-135.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 135,
  ),
  Song(
    title: "O Stworzycielu, Duchu przyjdź",
    site: 136,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-136.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 136,
  ),
  Song(
    title: "Obroną mi bądź",
    site: 137,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-137.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 137,
  ),
  Song(
    title: "Odszedł Pasterz od nas",
    site: 138,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-138.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 138,
  ),
  Song(
    title: "Ogrodzie Oliwny",
    site: 139,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-139.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 139,
  ),
  Song(
    title: "Oto jest dzień",
    site: 140,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-140.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 140,
  ),
  Song(
    title: "Oto Pan Bóg przyjdzie",
    site: 141,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-141.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 141,
  ),
  Song(
    title: "Oto Pan przybywa",
    site: 143,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-143.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 143,
  ),
  Song(
    title: "Oto są baranki młode",
    site: 144,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-144.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 144,
  ),
  Song(
    title: "Pan cię uchroni",
    site: 145,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-145.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 145,
  ),
  Song(
    title: "Pan i we śnie",
    site: 146,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-146.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 146,
  ),
  Song(
    title: "Pan ma wielką moc",
    site: 147,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-147.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 147,
  ),
  Song(
    title: "Pan odnowi twoje siły",
    site: 147,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-147.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 147,
  ),
  Song(
    title: "Pan Zastępów",
    site: 148,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-148.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 148,
  ),
  Song(
    title: "Panie dobry jak chleb",
    site: 150,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-150.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 150,
  ),
  Song(
    title: "Panie, dokąd pójdziemy",
    site: 151,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-151.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 151,
  ),
  Song(
    title: "Panie mój, cóż Ci oddać mogę",
    site: 152,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-152.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 152,
  ),
  Song(
    title: "Panie mój, nie jestem godzien",
    site: 153,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-153.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 153,
  ),
  Song(
    title: "Panie, pozostań",
    site: 154,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-154.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 154,
  ),
  Song(
    title: "Panu za wszystko dziękujemy",
    site: 154,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-154.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 154,
  ),
  Song(
    title: "Panie wysłuchaj modlitwy mojej",
    site: 155,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-155.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 155,
  ),
  Song(
    title: "Per Crucem",
    site: 156,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-156.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 165,
  ),
  Song(
    title: "Pieśń o nadziei",
    site: 157,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-157.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 157,
  ),
  Song(
    title: "Pieśń o Słudze Pańskim",
    site: 159,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-159.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 159,
  ),
  Song(
    title: "Płaczcie anieli",
    site: 160,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-160.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 160,
  ),
  Song(
    title: "Po upadku człowieka grzesznego",
    site: 161,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-161.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 161,
  ),
  Song(
    title: "Pod Twą obronę",
    site: 162,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-162.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 162,
  ),
  Song(
    title: "Podnieś mnie Jezu",
    site: 162,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-162.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 162,
  ),
  Song(
    title: "Podnieśmy sztandary miłości",
    site: 163,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-163.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 163,
  ),
  Song(
    title: "Pokładam w Panu ufność mą",
    site: 164,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-164.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 164,
  ),
  Song(
    title: "Powstań i świeć",
    site: 164,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-164.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 164,
  ),
  Song(
    title: "Pokój wam",
    site: 165,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-165.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 165,
  ),
  Song(
    title: "Powstań Przyjaciółko ma",
    site: 166,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-166.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 166,
  ),
  Song(
    title: "Pozostań z nami, Panie",
    site: 166,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-16.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 166,
  ),
  Song(
    title: "Przenikasz i znasz mnie",
    site: 167,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-167.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 167,
  ),
  Song(
    title: "Przybądź, Duchu Święty",
    site: 167,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-167.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 167,
  ),
  Song(
    title: "Przychodzisz Panie",
    site: 168,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-168.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 168,
  ),
  Song(
    title: "Przygotuj mocą nadziei",
    site: 168,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-168.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 168,
  ),
  Song(
    title: "Przyjdę do Was",
    site: 170,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-170.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 170,
  ),
  Song(
    title: "Przybądź Duchu Święty",
    site: 171,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-171.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 171,
  ),
  Song(
    title: "Przyjdź z pokłodnem, Ludu Boży",
    site: 171,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-171.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 171,
  ),
  Song(
    title: "Przyjmij o Najświętszy Panie",
    site: 172,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-172.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 172,
  ),
  Song(
    title: "Przykazanie nowe",
    site: 173,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-173.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 173,
  ),
  Song(
    title: "Psalm 8",
    site: 174,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-174.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 174,
  ),
  Song(
    title: "Psalm 40",
    site: 176,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-176.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 176,
  ),
  Song(
    title: "Psalm o miłosierdziu",
    site: 177,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-177.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 177,
  ),
  Song(
    title: "Radosna światłości",
    site: 178,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-178.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 178,
  ),
  Song(
    title: "Radujcie się!",
    site: 179,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-179.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 179,
  ),
  Song(
    title: "Regnavit Dominus",
    site: 180,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-180.png",
    type: "piesn",
    howMuchSites: 4,
    currSite: 180,
  ),
  Song(
    title: "Rorate caeli",
    site: 184,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-184.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 184,
  ),
  Song(
    title: "Różne są dary łaski",
    site: 186,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-186.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 186,
  ),
  Song(
    title: "Sekwencja wielkanocna",
    site: 187,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-187.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 187,
  ),
  Song(
    title: "Skosztujcie i zobaczcie - Bębenek",
    site: 188,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-188.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 188,
  ),
  Song(
    title: "Skosztujcie i zobaczcie - Kusz",
    site: 189,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-189.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 189,
  ),
  Song(
    title: "Sław języku tajemnicę",
    site: 190,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-190.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 190,
  ),
  Song(
    title: "Słodkie jest brzemię",
    site: 191,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-191.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 191,
  ),
  Song(
    title: "Spotkają się",
    site: 192,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-192.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 192,
  ),
  Song(
    title: "Strumienie",
    site: 193,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-193.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 193,
  ),
  Song(
    title: "Światłem i zbawieniem mym",
    site: 194,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-194.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 194,
  ),
  Song(
    title: "Święta Dziewico",
    site: 195,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-195.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 195,
  ),
  Song(
    title: "Szukajcie wpierw Królestwa Bożego",
    site: 196,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-196.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 196,
  ),
  Song(
    title: "Tak bowiem Bóg",
    site: 197,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-197.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 197,
  ),
  Song(
    title: "Ten, który słowem",
    site: 198,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-198.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 198
  ),
  Song(
    title: "Tobie wznawiamy",
    site: 199,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-199.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 199,
  ),
  Song(
    title: "Tobie ufam Boże",
    site: 200,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-200.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 200,
  ),
  Song(
    title: "Twoja sprawiedliwość",
    site: 201,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-201.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 201,
  ),
  Song(
    title: "Twoja cześć",
    site: 202,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-202.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 202,
  ),
  Song(
    title: "Twoje Słowo jest lampą",
    site: 203,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-203.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 203,
  ),
  Song(
    title: "Tylko w Bogu",
    site: 203,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-203.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 203,
  ),
  Song(
    title: "Tylko w Twoim miłosierdziu",
    site: 204,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-204.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 204,
  ),
  Song(
    title: "Tyś jest ponad cały świat",
    site: 205,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-205.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 205,
  ),
  Song(
    title: "U Ciebie Boże",
    site: 206,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-206.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 206,
  ),
  Song(
    title: "U drzwi Twoich stoję Panie",
    site: 207,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-207.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 207,
  ),
  Song(
    title: "Uczta Baranka",
    site: 208,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-208.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 208,
  ),
  Song(
    title: "Ukaż mi Panie swą twarz",
    site: 209,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-209.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 209,
  ),
  Song(
    title: "Umocnij nas Chryste",
    site: 210,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-210.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 210,
  ),
  Song(
    title: "Upadnij na kolana",
    site: 210,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-210.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 210,
  ),
  Song(
    title: "Urząd zbawienia ludzkiego",
    site: 211,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-211.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 211,
  ),
  Song(
    title: "Veni, veni, Emmanuel",
    site: 212,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-212.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 212,
  ),
  Song(
    title: "W tobie jest światło",
    site: 213,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-213.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 213,
  ),
  Song(
    title: "Wesel się Królowo Miła",
    site: 214,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-214.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 214,
  ),
  Song(
    title: "Wesoły nam dzień dziś nastał",
    site: 214,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-214.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 214,
  ),
  Song(
    title: "Wielki jest Pan",
    site: 216,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-216.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 216,
  ),
  Song(
    title: "Wielkie i dziwne są dzieła Twoje",
    site: 217,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-217.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 217,
  ),
  Song(
    title: "Wisi na krzyżu",
    site: 217,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-217.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 217,
  ),
  Song(
    title: "Wielkie są dzieła",
    site: 218,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-218.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 218,
  ),
  Song(
    title: "Witaj Gwiazdo morza",
    site: 219,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-219.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 219,
  ),
  Song(
    title: "Witaj Pokarmie",
    site: 220,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-220.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 220,
  ),
  Song(
    title: "Wody Jordanu",
    site: 220,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-220.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 220,
  ),
  Song(
    title: "Wróć duszo moja",
    site: 222,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-222.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 222,
  ),
  Song(
    title: "Wszystkie nasze dzienne sprawy (Kiedy ranne wstają zorze)",
    site: 223,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-223.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 223,
  ),
  Song(
    title: "Wszystko Tobie oddać pragnę",
    site: 224,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-224.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 224,
  ),
  Song(
    title: "Wszystko co żyje",
    site: 225,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-225.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 225,
  ),
  Song(
    title: "Z dawna Polski",
    site: 226,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-226.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 226,
  ),
  Song(
    title: "Zaufaj",
    site: 227,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-227.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 227,
  ),
  Song(
    title: "Zawitaj, Królowo Różańca Świętego",
    site: 228,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-228.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 228,
  ),
  Song(
    title: "Zawitaj ranna Jutrzenko",
    site: 229,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-229.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 229,
  ),
  Song(
    title: "Zawitaj ukrzyżowany",
    site: 230,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-230.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 230,
  ),
  Song(
    title: "Zbliżam sie w pokorze - Bębenek",
    site: 231,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-231.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 231,
  ),
  Song(
    title: "Zbliżam sie w pokorze - Kotek",
    site: 232,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-232.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 232,
  ),
  Song(
    title: "Zbudź się!",
    site: 234,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-234.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 234,
  ),
  Song(
    title: "Zbudź się o śpiący",
    site: 235,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-235.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 235,
  ),
  Song(
    title: "Zdrowaś bądź Maryja",
    site: 236,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-236.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 236,
  ),
  Song(
    title: "Zdrowaś Maryja",
    site: 237,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-237.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 237,
  ),
  Song(
    title: "Zmiłuj sie nade mną",
    site: 238,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-238.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 238,
  ),
  Song(
    title: "Znalazłam Umiłowanego",
    site: 238,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-238.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 238,
  ),
  Song(
    title: "Życie jesteś chwilą",
    site: 239,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-239.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 239,
  ),
  Song(
    title: "Zwycięzca śmierci",
    site: 240,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-240.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 240,
  ),
  Song(
    title: "Dobrze jest Tobie śpiewać",
    site: 241,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-241.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 241,
  ),
  Song(
    title: "Modlitwa przed posiłkiem (Boże, dzięki Ci składamy)",
    site: 242,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-242.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 242,
  ),
  Song(
    title: "Święty Macieju",
    site: 243,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-243.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 243,
  ),
  Song(
    title: "O salutaris Hostia",
    site: 244,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-24.png",
    type: "piesn",
    howMuchSites: 2,
    currSite: 244,
  ),
  Song(
    title: "Radością brzmi niebo całe",
    site: 246,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-246.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 246,
  ),
  Song(
    title: "Vexilla Regis",
    site: 247,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-247.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 247,
  ),
  Song(
    title: "Złożyłeś Panie",
    site: 248,
    imageUrl: "lib/Screens/pictures/NŚM v.2.0-248.png",
    type: "piesn",
    howMuchSites: 1,
    currSite: 248,
  ),
];